### ISSUE TITLE
applet icon suggestions

### ISSUE THREAD

**Issue by Sadi58** [tubbadu/Scriptinator#13]
The current icon looks like a toy/paint gun, IMHO.
I thought a better one can be selected from amongst suggestions here.
To start with, I have the following suggestion, which is just 13.6 Kb although the scalable image size is 512 px:
![scriptinator](https://user-images.githubusercontent.com/6375934/214590249-8d0d35e6-44bc-442a-971b-1b521f8c5b00.svg)

**Comment by Sadi58** [comment]
Hmm, on second thought, I think it might be a better idea to use one of the existing system icons, and leave the user to choose a custom icon if they wish (like mine above).
In addition to `dialog-scripts`, and `format-text-code` above, I think other relevant system icons might be: `utilities-terminal`, `plasma-nano`, and `smart-git`.
Perhaps, one of the last two would look nicer.
![utilities-terminal](https://user-images.githubusercontent.com/6375934/214617034-0902e1ca-f7b6-4121-9cb4-f56f01531cfc.svg)
![plasma-nano](https://user-images.githubusercontent.com/6375934/214616389-cfe2fdf2-0987-49a8-a7f3-29bc23f195ca.svg)
![smartgit](https://user-images.githubusercontent.com/6375934/214616457-20c8a74c-0baa-48b7-a077-a26429b57009.svg)

**Comment by tubbadu** [comment]
I really like the plasma-nano icon! in the version 3.0 then I'll use one of these icons, so the installation process will be simpler

**Comment by Sadi58** [comment]
Having decided to use the stock icon `utilities-terminal`, you might like to update `install.sh`, and and remove the sub-directory `img` maybe.
BTW, the screenshot in **KDE Store** also needs updating, which might also be included in the `README.md` file.

**Comment by tubbadu** [comment]
in the next push I'll remove the install.sh and the img folder as not needed anymore, to install will be necessary just a single command (`plasmapkg2 --install filename.plasmoid`) that I will write inside the readme

>  BTW, the screenshot in KDE Store also needs updating, which might also be included in the README.md file.
I totally forgot about this! I'll fix this as soon as possible, perhaps with some GIF to show how it works
