### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by Sadi58** [tubbadu/Scriptinator#15]
I think it might be a good idea to share somewhere here some **examples** of how **Scriptinator** may be used.
Actually, opening a **Discussions** section could serve this purpose better (like the one here: [https://github.com/WAClient/WALC/discussions](https://github.com/WAClient/WALC/discussions))

**Comment by tubbadu** [comment]
#18 is the first example included (thanks to @jinliu !)
I'll add others as soon as I can!

**Comment by Sadi58** [comment]
One of these days I'll stop tinkering and share my "_plasma-discover-update_ replacement" implementation of **Scriptinator**. ;-)
It enables the user to view which packages are ready to update, and then to choose _Discover_, _Apper_ or _Konsole_ to perform those updates.
I'm also hoping very amateur scripts can be improved by a skilled and experienced person.
