### ISSUE TITLE
Is there a way to run a script at startup with Scriptinator or controlling it externally?

### ISSUE THREAD

**Issue by rizzini** [tubbadu/Scriptinator#2]
I need to run my script at startup. Without the possibility of running my script at startup with Scriptinator, I'd need to create some kind of execution control, which is not great. Another way would be controlling Scriptinator externally. Are one of these possible?

Amazing job, man. Keep it up.

**Comment by tubbadu** [comment]
You're right, it is easily misunderstood, I'll update the description to make it more intuitive! thanks man!
Controlling Scriptinator externally should be possible I think, but I don't have the slightest idea on how to do this! It would be really handful however, I'll add it to the "Difficult TODOs" list
