### ISSUE TITLE
port to plasma 6

### ISSUE THREAD

**Issue by tubbadu** [tubbadu/Scriptinator#22]
https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by Sadi58** [comment]
I wish Plasma 6 came with a wizard tool to port Plasma 5 widgets to Plasma 6. 😄

**Comment by tubbadu** [comment]
plasmoid successfully ported to Plasma 6 with commit [24c220b](https://github.com/tubbadu/Scriptinator/commit/24c220ba13217130adc92f9e4626bedf6ee5b1b1). The plasma 5 version is still available in the [plasma5-branch](https://github.com/tubbadu/Scriptinator/tree/plasma5-branch) branch. I hope everything has been ported correctly, in case of issues I'll try to fix them as soon as I can
