### ISSUE TITLE
Configuration dialog box: Instruction

### ISSUE THREAD

**Issue by Sadi58** [tubbadu/Scriptinator#3]
It seems  there's a problem with text color definition. It should be black when using light theme, and white when using dark theme maybe?
Secondly, shouldn't the text be wrapped instead of being cut off like that?
Also, I would suggest naming it "Help" instead of "Instruction", and moving after the General/Settings.
![2022-12-12_16-03-47_Screenshot](https://user-images.githubusercontent.com/6375934/207052906-acbe5a2b-c3af-48e8-b88a-6d74cf31077a.jpg)

**Comment by tubbadu** [comment]
Thanks for the suggestion, I fixed this in the last push!
