### ISSUE TITLE
Cofiguration : General text suggestions

### ISSUE THREAD

**Issue by Sadi58** [tubbadu/Scriptinator#6]
It would be better to make the following lines of text wrap automatically when the window width is reduced by user:

- OnClick icon...
- WheelUp script...
- WheelDown script...
- OnMouseOver script...
- Set custom height and width...

Also I suggest the following changes for the text here:

- OnClickScript -> OnClick script
- PeriodicScript script -> Periodic script
- when the mouse hover the widget's area -> when the mouse hovers over the widget
- placed in the desktop -> placed on the desktop
- use custom tooltip -> Use custom tooltip
- showTooltip option -> Show tooltip option
- last-run command -> last run command

**Comment by tubbadu** [comment]
I'll fix this as soon as possible! thanks for the help, it's very precious to me!

**Comment by tubbadu** [comment]
> It would be better to make the following lines of text wrap automatically when the window width is reduced by user

the problem seems to be that the TextField element's width should be set to `parent.width`, but if the window is too small it ignores the parent width and set its width to 552

I'll have to find out why

**Comment by Sadi58** [comment]
This is what happens here when I reduced window width to minimum, but it's interesting to see some lines wrapping very nicely.
![2023-01-24_15-26-33_Screenshot](https://user-images.githubusercontent.com/6375934/214292071-37e1244f-6b02-4fb8-8761-bc512855ff66.jpg)

**Comment by tubbadu** [comment]
I managed to workaround this strange behaviour, I'll release the updated version as soon as possible
