### ISSUE TITLE
How to make use of "Show when relevant"

### ISSUE THREAD

**Issue by Sadi58** [tubbadu/Scriptinator#7]
It's very handy to see this plasmoid listed in system tray entries.
However, it would be great if users could have some info (e.g. in the Help section) how to make specify when this plasmoid is shown or hidden in the system tray.

**Comment by tubbadu** [comment]
currently that feature is experimental, but in the future I'd be really happy to add a full support to this feature:
* possibility to change "relevant" state to relevant and not relevant
* possibility to display more than just one in the system tray (I don't know if it's possible, currently I just copy paste the widget changing plasmoid name, but it's definitely not the best option XD )

thanks for the feedback!!!

**Comment by Sadi58** [comment]
I've started using Scriptinator (instead of Command Output) as a replacement for the default Update Notifier, because in some cases, e.g. when an isolated application has a pending update, it makes more sense to perform the update online (without rebooting the machine twice), while in some cases it is safer to do it offline (e.g. when system packages currently in use are involved).
I think what I have now is better than the default setup, but it could be even better if it didn't show an icon in the system tray when there are no pending updates, although one could argue as well that it's better to display a "system is up-to-date" icon. ;-)
![2023-01-24 14-38-49_000000006](https://user-images.githubusercontent.com/6375934/214294439-eb43d1d3-f24b-4770-ae4c-e462535b4713.jpg)
![2023-01-24_14-51-55_Screenshot](https://user-images.githubusercontent.com/6375934/214294443-c5fb3235-a904-4437-9058-97c0565dabde.jpg)

**Comment by tubbadu** [comment]
Here we are! Now it is possible to change the status of the plasmoid in the system tray using
```{PlasmoidStatusStart}insert new status here{PlasmoidStatusEnd}```
check out on the readme for the possible values!

thanks for the suggestion, it's very very useful in my opinion! it will surely have bugs and problems but I'll solve them as soon as possible!

**Comment by Sadi58** [comment]
Wov! It works! Thank you! Now I have an Update Notifier even better than KDE Plasma's own. 😉
![2023-01-25_14-53-11_Screenshot](https://user-images.githubusercontent.com/6375934/214557636-2150d577-86ba-4268-8aa5-4c80f0410c4b.jpg)
